### PR TITLE
Order them better maybe

### PR DESCRIPTION
**Pull request by licaon-kter**
...and you just updated the screenshots... sorry :)

### CODE REVIEW

**Comment by M66B** [comment]
The order is the same as in the application slide down settings.
The reason for this existing order is that there is a dependency between these two settings.

**Comment by okungnyo** [comment]
Order what?

(Sorry, I'm just curious.)

**Comment by M66B** [comment]
@okungnyo the preferences (settings).

**Comment by licaon-kter** [comment]
What are *"application slide down settings"* exactly ?

**Comment by M66B** [comment]
@licaon-kter the settings which appear when you tap on an application name in the application list

**Comment by licaon-kter** [comment]
Ok

**Comment by okungnyo** [comment]
Thanks.

**Pull request closed without merging**
