### PR TITLE
Markup issues fix

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by M66B** [comment]
Extra spaces? They should not be need, but maybe I am wrong.

**Comment by licaon-kter** [comment]
I my browser they ended up as: * feature * feature * feature

instead of:
* feaure
* feature
* feature

Is this looking ok for you: https://github.com/M66B/NetGuard/blob/6f6b761ebd952ff55583dd05d82c224980e031cb/PLAY.md ? 
Not for me at least in Firefox and Opera.

**Comment by M66B** [comment]
In the Play store this will show properly.

**Comment by licaon-kter** [comment]
Oh right.

**Pull request closed without merging**
