### PR TITLE
Remove usage stats info if not actually tracked

### PR DESCRIPTION
**Pull request by licaon-kter**
(to be merged after `lockdown` branch)

### CODE REVIEW

**Comment by licaon-kter** [comment]
Not sure I follow.
This should just remove the +0.00/+0.00MB/day useless text from app view, the graph still works afaics.

**Comment by M66B** [comment]
I misunderstood, but the traffic stats are also independent of filtering/logging.

If these are zero, then your Android version (which?) doesn't support traffic stats. Unfortunately there is no API to check if these stats are supported. Querying for all apps to see if everything is zero is no option.

**Comment by licaon-kter** [comment]
Samsung 6.0.1 & Xperia 6.0.1

Neither have the compound stats, BUT (if _track_usage_ is on) have per domain stats.
I remember this working, but on 5.1.1/5.0.2, and having _track_usage_ off 100% of the time I thought this might be at fault.

In Android settings, network stats I do have per app traffic info.

**Comment by M66B** [comment]
The track usage setting will track the number of bytes sent/received per connection, not for the app as total, which is delivered by Android:
https://developer.android.com/reference/android/net/TrafficStats.html

**Comment by M66B** [comment]
Could you please try compiling with the above commit?
I can't test this on Android 7 Nougat ...

**Comment by licaon-kter** [comment]
> which is delivered by Android

So if Android delivers (per that link) the value of `UNSUPPORTED` as `-1` then [your](https://github.com/M66B/NetGuard/blob/673810cca62598f950d5d6d2842dec5425101aa2/app/src/main/java/eu/faircode/netguard/ServiceSinkhole.java#L801) code will just make it zero?

Will check later today.

**Comment by M66B** [comment]
Yes, but there is more in the commit ...

**Comment by licaon-kter** [comment]
Got around to test this and works as expected.

Learn one more thing, while the Android stats list all apps usage, if I sort apps by usage in NetGuard the very first app, and the only one with stats visible (aka not zero) is... NetGuard.

**Comment by M66B** [comment]
I guess you have filtering mode enabled.
This can be considered to be a bug in your Android version. It seems to be fixed in Android 7 Nougat.

**Comment by licaon-kter** [comment]
Yes, filtering is ON, although I'm not seeing anything different with it off, NetGuard stats get updated, but all the other apps have none (zero).

**Pull request closed without merging**
