### PR TITLE
Update FAQ with info on AFWall+

### PR DESCRIPTION
**Pull request by licaon-kter**
I said *current* since host blocking is not an official feature yet ;)

### CODE REVIEW

**Comment by M66B** [comment]
I think this was nicely written down!
Can you please add a link to the FAQ from the README as well?

**Comment by M66B** [comment]
AFWall+ has one advantage though: it can prevent leaking during startup, although I am not sure if this works properly. For the rest NetGuard has a few nice extra features, which AFWall+ doesn't have.

**Comment by M66B** [comment]
AFWall+ will use less battery.

**Comment by licaon-kter** [comment]
The leak protection needs root aka true init.d support in ROM, which might need a custom ROM on an bootloader unlocked device... how many of those are there in % ?

If no kernel init.d support you'll need an emulated init.d that's just an app that starts on bootdone intent and runs some stuff, which you already do but it does not fix that.

In my tests, on a rooted device I always ended up with all traffic blocked somehow, when having AFWall+s iptables script in init.d, so YMMV.

I'll mention `hosts block for GitHub builds` once those are in README.md ;)

**Pull request merged**
