### PR TITLE
Check for VpnDialogs package

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by M66B** [comment]
Are you sure that this works?
Can it detect an installed VPN dialog package?
Can it detect an absent VPN dialog package?

**Comment by pylerSM** [comment]
yes, VPN dialog package is normal android package. If missing, VPN confirm will crash for sure.

**Comment by M66B** [comment]
Okay, that is good, but how do we know that the package name is the same on all devices? It is called '*com.android.vpndialogs*' in AOSP, but do all manufacturers call it the same? I am afraid this is not the case, which would result in false negatives. IMHO is it better to let NetGuard crash if somebody removed the VPN dialog package, because then that somebody has root permissions and hopefully knows how to handle broken things. I didn't encounter Android versions with a missing VPN dialog so far (no-root users).

**Comment by pylerSM** [comment]
I believe no vendor changed com.android.vpndialogs package name...
But yes. you have the truth. no root users cant remove it anyway.

**Comment by kyze8439690** [comment]
Some ugly rom did remove this package for unknown reason.

**Comment by M66B** [comment]
Too bad for you.

**Pull request closed without merging**
