### PR TITLE
filter log by ip

### PR DESCRIPTION
**Pull request by rgarza**
Filter log by IP.

### CODE REVIEW

**Comment by M66B** [comment]
Thanks, this is a nice addition!

**Comment by M66B** [comment]
It does not work for me, so I have undone the pull request.

**Comment by rgarza** [comment]
Ok, i will check what i missed, seems to work fine for me in Emulator and phone, will check later today.

**Comment by rgarza** [comment]
I found the problem, seems i missed one call in the onQueryTextChange, but now with the call to resolve the ip makes it hard to filter just by Ip address it should be allowed to filter by hostname, but since thats resolved dynamically that cannot be done in sql side, do you have any preference on how to handle?, would it be better store all data in SQLite? for easier searching? but maybe file would grow a lot.

**Comment by M66B** [comment]
Yes, with the new host name resolution it will be harder.

Note that for effectively querying the database the IP address needs to be indexed. This has as disadvantage that writing new records will be more expensive.

My advice is to wait with this until I am finished with the native code, since there could be more changes in the way logging is been done (currently there is a performance problem with it).

**Comment by M66B** [comment]
If you want, you can do another try, because I have done the database changes I planned to do (for now). I have also added an index on 'daddr' (formerly 'ip') to facilitate searching. There is also a new menu option to disable/enable host name resolving.

**Pull request merged**
