### PR TITLE
Update Simplified Chinese translation

### PR DESCRIPTION
**Pull request by ContactFront**

### CODE REVIEW

**Comment by M66B** [comment]
I am not sure of the texts "running" and "stopped" yet.
Running could be something like "Blocking selected applications".
Stopped could be something like "Allowing all internet".

**Comment by ContactFront** [comment]
ok. should I revert the changes and wait for you to finalize?

**Comment by M66B** [comment]
The texts are now definitive, so you can translate the new texts.

Maybe wait a little, because more texts are coming ...

**Comment by M66B** [comment]
If you like, you can translate the new texts now.

**Pull request closed without merging**
