### PR TITLE
Many improvements

### PR DESCRIPTION
**Pull request by Gitoffthelawn**

### CODE REVIEW

**Comment by M66B** [comment]
Thank you very much!
This is highly appreciated!

**Comment by M66B** [comment]
Can you please take a look here too?
http://www.netguard.me/

**Comment by Gitoffthelawn** [comment]
You are quite welcome! Glad to give you a hand.  :-)

The netguard.me site now looks good as well.  The only error is that the Paypal link does not look like a hyperlink (it looks like normal non-clickable text in most browsers).  This is because it is a `form input`, and not an `a href`.  The solution is to convert it to `a href` or to apply the link color manually.

**Comment by M66B** [comment]
The PayPal donation should be displayed as a clickable icon, which for me it does.

**Comment by licaon-kter** [comment]
Do put that screenshot on the right side of the website, it makes the point better.

**Comment by M66B** [comment]
Which screen shot do you mean?

**Comment by licaon-kter** [comment]
Any

**Comment by Gitoffthelawn** [comment]
I took another look at the PayPal issue.  It is *not* an issue with your site.  I restrict access to all external calls to PayPal sites unless certain parameters are met.  As a result, the PayPal image does not appear and I see the alternate text.

I don't see it as an issue, as long as you are aware that others may block third-party content as well.

In regards to the suggestion by @licaon-kter, I think it is a good one.  A screenshot of NetGuard on the netguard.me site is a good idea.  As netguard.me starts to appear in search engines, it may be the starting point of people being introduced to NetGuard.

**Comment by licaon-kter** [comment]
Get the updated [one](https://github.com/M66B/NetGuard/blob/master/screenshot.png)

**Comment by M66B** [comment]
I first didn't understand the suggestion, but it is actually a good suggestion, so thanks @licaon-kter 
How does it look like this?
http://www.netguard.me/

**Comment by licaon-kter** [comment]
Looks smaller, better make it 100%.

**Comment by M66B** [comment]
It should display on mobile devices okay too.

**Comment by M66B** [comment]
@Gitoffthelawn I have replaced the external PayPal image by a self hosted image now, so it should display correct now.

**Comment by Gitoffthelawn** [comment]
The self-hosted PayPal image works well.  The screenshot does too, but I agree it's a bit small on a desktop screen (although, as you point out, it looks good on a mobile device, which is the primary audience).

**Comment by M66B** [comment]
I have made the image clickable as a compromise.

**Comment by Gitoffthelawn** [comment]
That works!  :-)

**Comment by licaon-kter** [comment]
Also add [the preference picture](https://github.com/M66B/NetGuard/blob/master/screenshot2.png) on the site.

**Comment by M66B** [comment]
That would use quite some space when viewing on a small screen (mobile devices).

**Comment by licaon-kter** [comment]
So I see that now, maybe do it differently, on click show [a combined image](https://imgur.com/a/7jMjY)

**Comment by M66B** [comment]
It is a good idea, but it is to wide for small screens.
The screenshot itself is already the size of a screen (obviously).

**Comment by licaon-kter** [comment]
Users can zoom in/out :)

**Comment by M66B** [comment]
I don't think the settings page is the most important to show.
Even without using the settings page at all, NetGuard is quite usable!

**Comment by licaon-kter** [comment]
I do agree though.

**Comment by licaon-kter** [comment]
BTW http://blog.bokhorst.biz/about/ yields a 404

**Comment by M66B** [comment]
Fixed by changing the URL.

**Comment by licaon-kter** [comment]
And the *About me* page there too, come on :)

**Comment by M66B** [comment]
Should be changed.
Maybe cached?
I cannot find other settings on GitHub.

**Comment by licaon-kter** [comment]
On faircode.eu I mean.

**Comment by M66B** [comment]
Fixed too, thanks.

**Comment by licaon-kter** [comment]
And your name at Copyright lower left :):)

**Comment by M66B** [comment]
Also fixed, thanks for your sharp eye!

**Pull request merged**
