### PR TITLE
AndroidManifest.xml: Enable backups

### PR DESCRIPTION
**Pull request by genodeftest**
Having a backup of the rules configuration would be very useful in case of data loss.

Background:
As smartphones can easily be lost or get stolen or break, it is useful to have regular backups. I recommend to back up the smartphone at least once a month or even once per week. Prior to this change, NetGuard would not be backed up, i.e. in case of data loss and the user restoring a backup, both the NetGuard app and all its config would be missing.

### CODE REVIEW

**Comment by M66B** [comment]
For privacy reasons Google backups are deliberately disabled.

**Comment by genodeftest** [comment]
Is there any other way to get automated backups of NetGuard? Having to click through the GUI for each and every application to create a backup raises the barrier for automated backups unnecessarily.

**Comment by M66B** [comment]
There is an export for this. When needed, please continue this discussion on XDA.

**Comment by genodeftest** [comment]
> There is an export for this. When needed, please continue this discussion on XDA.

Done: https://forum.xda-developers.com/android/apps-games/app-netguard-root-firewall-t3233012/post78919463#post78919463

**Pull request closed without merging**
