### PR TITLE
Update German strings.xml

### PR DESCRIPTION
**Pull request by User99gmxat**
Wi-Fi is a trademark, a syndicate which certified wireless interfaces. An art-term. Sometimes WiFi will be used insted of WLAN in German, but for me here WLAN makes more sense.

### CODE REVIEW

**Comment by M66B** [comment]
Thanks!

**Comment by User99gmxat** [comment]
Your're welcoem. Another question: What do you mean exactly with 'metered Wi-Fi networks'?

**Comment by M66B** [comment]
Metered = pay for traffic used.

**Comment by User99gmxat** [comment]
Ok, then I did it right ;)

**Pull request merged**
