### PR TITLE
Update Romanian description

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by M66B** [comment]
What is your opinion about the current (English) Play store description?

**Comment by licaon-kter** [comment]
You cut a big chunk, no rewrite?

And you already know my opinion on clear descriptions, aka:
* `(PRO)` Optionally log traffic/display network speed graph
* Material design, with selectable theme `(PRO 5 more)`

**Comment by M66B** [comment]
I value your opinion, so please do a pull request about how you would describe NetGuard

**Comment by licaon-kter** [comment]
You'll weed out some of the 1stars that have a problem with the `pay for this` view popping up.
Like I said, I would like a `PRO` prefix, a ★ or something inside the app too, to sigle out features that would yield the PRO features view..

**Pull request merged**
