### PR TITLE
Misc compatibility settings

### LINKED ISSUE #345: Port redirection issues
Set a custom DNS and then change connection status (disconnect/Wi-Fi/mobile).

### PR DESCRIPTION
**Pull request by licaon-kter**
In debugging for now:
* forcerestart - fix #345 for ROMs that bypass the VPN for DNS calls on switch to mobile (eg. Xperia 5.1.1) by using the same reload method (destroy VPN) as used already for SDK<22
* routedns - https://github.com/M66B/NetGuard/commit/7673dceb8df28d76bc0ba5b085b41249d26e8b82 with a toggle ([might help some Samsung users](https://github.com/schwabe/ics-openvpn/blob/3ebdb6482f3bab9423436e6b208963d5d7c07656/main/src/main/java/de/blinkt/openvpn/core/OpenVPNService.java#L590))
* ignoresysdns - create VPN without system DNS servers, if no server is set up in app then Google's 8.8.8.8 is used

### CODE REVIEW

**Comment by M66B** [comment]
Sorry, but I don't want to be this part of the source code.

**Comment by licaon-kter** [comment]
Not even the fix for #345?

**Comment by M66B** [comment]
* Force restart: fine with me in the debug settings
* Route DNS: I don't think this will fix anything and risk only breaking things
* Ignore system DNS: fine with me in the debug settings, but handle the setting in getDefaultDNS, so that the upper layers don't need to be modified

**Comment by licaon-kter** [comment]
Force restart - better limit it to my case ` || ("Sony".equals(Build.BRAND) && Build.VERSION.SDK_INT == Build.VERSION_CODES.LOLLIPOP_MR1)` then ?

Route DNS - not really caring about it, hope it is helpful to someone though

Ignore system DNS - same. I did try it in *getDefaultDNS* too, but it's only moving the last `if (ignoresys)` so I did not feel it was an improvement.

**Comment by M66B** [comment]
Device specific workarounds will not be very maintainable, so better a debug setting.

Just let *getDaultDNS* return 8.8.8.8 only when the settings is enabled.

**Comment by licaon-kter** [comment]
Force restart - just merge the first patch from this PR
Ignore system DNS - see https://github.com/M66B/NetGuard/pull/356

**Comment by licaon-kter** [comment]
Again, I only want forcerestart for #345 
I made a PR #356 for ignoresysdns since, given your advice above, I thought you might want/find it useful

**Comment by M66B** [comment]
If there is no use case, I see no point in adding a new setting.
I have my doubts about the force restart, because I rather find the cause of the problem.

**Pull request closed without merging**
