### PR TITLE
Create values-ru

### PR DESCRIPTION
**Pull request by Ivan4537**

### CODE REVIEW

**Comment by M66B** [comment]
I really appreciate your contribution, but please follow these directions:
https://github.com/M66B/NetGuard#contributing

At this moment there are too many texts translated, which will give problems.

**Comment by Ivan4537** [comment]
Sorry, I've been on this site for the first time, and don't quite understand how to work here.

**Comment by M66B** [comment]
No problem at all.
I will try to fix this tomorrow.

**Comment by Ivan4537** [comment]
I noticed a bug. After its translation into Russian of the application menu disappears button "Invite". Don't know what it involves.

**Comment by M66B** [comment]
I have fixed the translation and it will be included in the next release.
Thanks for translation and helping Russian people not so fluent in English!

**Comment by Ivan4537** [comment]
With the development of your program will update the translation :)

**Comment by M66B** [comment]
Thanks there is already to do something ;-)
https://github.com/M66B/NetGuard/blob/master/app/src/main/res/values-ru/strings.xml

**Pull request merged**
