### PR TITLE
Tamil string updates

### PR DESCRIPTION
**Pull request by mfap-aravinth**
Updated a portion of tamil strings, Hope this helps :)

### CODE REVIEW

**Comment by M66B** [comment]
Thanks for this. But unfortunately I cannot merge this because translations are imported from [Crowdin](https://crowdin.com/project/netguard). So, your changes would be overwritten on the next import.

**Comment by mfap-aravinth** [comment]
Understood 👍

**Comment by M66B** [comment]
I have just imported your translations in Crowdin. Maybe you can check.

**Comment by mfap-aravinth** [comment]
Not familiar with that site, let me check..

**Pull request closed without merging**
