### PR TITLE
Setting to show allow/block notification as heads-up

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by M66B** [comment]
I want to keep the number of settings to a minimum (there are already too many) and I am not sure if people really want this. Nobody has ever asked about it.

**Comment by licaon-kter** [comment]
When does this appear? I hope not every time NetGuard reapplies settings or such, those happen a lot, specially when changing network (types), dozing, powersaving and what not.

**Comment by pylerSM** [comment]
When new app installed to configure NetGuard.

**Comment by pylerSM** [comment]
You can test... Just install new app to see heads up notification: http://www19.zippyshare.com/v/gW92kGq8/file.html

**Comment by licaon-kter** [comment]
Oh, on app install, now I get it.
It could be something yes, now this would work, imho, by either having the notification or the heads-up, maybe the settings toggle could switch between them.

**Comment by pylerSM** [comment]
If you dont enable Heads up notification => you get normal notification
If you enable it => you get Heads up notification

**Comment by M66B** [comment]
I have been thinking about this, but high priority notifications should only be used for reality important things, like incoming calls and weather alerts, but not to notify about newly installed applications. The Google Play store notifications are similar and are normal priority notifications as well. Personally I would hate this feature.

**Pull request closed without merging**
