### PR TITLE
Update order of optionals

### PR DESCRIPTION
**Pull request by licaon-kter**
Grouped they are more readable

### CODE REVIEW

**Comment by M66B** [comment]
Perfectionist? ;-)
This needs to be done for the Play store description as well.

**Comment by licaon-kter** [comment]
O RLY?

**Comment by M66B** [comment]
I recognize one, since I am one myself ;-)

**Comment by licaon-kter** [comment]
Funny that the reason I tested this app initially ( no root firewall for the A5 ) is actually useless.

**Comment by M66B** [comment]
Better: funny that your ROM is useless for this application.

**Comment by licaon-kter** [comment]
Right.

**Comment by M66B** [comment]
Maybe you like to chat: XMPP: marcel@faircode.eu
(I will remove this message later to prevent indexing of my e-mail address)

**Comment by licaon-kter** [comment]
Got it, you can remove it.

**Comment by licaon-kter** [comment]
Still visible [here](https://github.com/M66B?tab=activity)

**Comment by M66B** [comment]
Hmmm

**Pull request merged**
