### PR TITLE
Attempting to redirect 'no' to 'nb'

### PR DESCRIPTION
**Pull request by DandelionSprout**
To the degree I understood your comments on #515, and Linux command line syntaxes, I've now instead attempted to tie values-no to values-nb, on the presumption that it'll make the Norwegian Crowdin translation project apply to both of those files.

### CODE REVIEW

**Comment by M66B** [comment]
I will look into this next week.

Op zo 29 jul. 2018 11:26 schreef Imre Kristoffer Eilertsen <
notifications@github.com>:

**Comment by M66B** [comment]
Am I correct that 'nb' is Norwegian Bokmål ?

**Comment by M66B** [comment]
Could you please check if everything is okay in this release?
https://github.com/M66B/NetGuard/releases/tag/2.205

**Comment by DandelionSprout** [comment]
Yes, I can confirm that 'nb' is Norwegian Bokmål (which is the most used written version of Norwegian by far), and that the coding of the 2.205 branch looks spotless to me. 👍

**Pull request merged**
