### PR TITLE
 use new session per ICMP ID

### PR DESCRIPTION
**Pull request by top-master**
restore ICMP id change and use new session instead:
I always try to save memory but this wents this time bad, we do need a new session for each port/id or ICMP will never work right.

### CODE REVIEW

**Comment by M66B** [comment]
Did you check if this doesn't use too many file descriptors? Most devices allow only 1024 file descriptors per app.

**Comment by top-master** [comment]
will check now

**Comment by top-master** [comment]
this means I think there are just 15 file descriptors used by that ping monster

**Comment by M66B** [comment]
That is too much in my opinion. There are already too many problems with running out of file descriptors.

**Comment by top-master** [comment]
**15** will only be the case if someone does run that ping app else it will be **zero** I do not think that anyone will run that app and try to use net beside it and leave that in background.
but may be they use [this](https://apkpure.com/ping/com.lipinic.ping) or any other ping app to test a web-site IP someday.

anyway it would be bad when [this](https://apkpure.com/ping/com.lipinic.ping) or any other ping app just prints "time out" when the [firewall/NetGuard](https://apkpure.com/netguard-no-root-firewall/eu.faircode.netguard) is active, leaving this as is will help no one since no one will run ping in background

**Comment by top-master** [comment]
I currently do combine NetGuard with a VPN which does use only one L2TP connection to simulate HTTPS sessions.
and did find out that problem in NetGuard side as we was testing the ICMP of our VPN side anyway will now continue on that VPN side and leave NetGuard side for now

**Comment by M66B** [comment]
Many apps do pings to check connectivity, so it will not just be ping apps.

**Comment by top-master** [comment]
but the ICMP session count by me when not running that app is zero and if there is an app that does use ping it will for sure not try to kill the server with as many Ping requests as it can like [this](https://apkpure.com/ping/com.lipinic.ping) one.

anyway what I mean is usually there are just few requests (4 by default) made and all to same port which will only use **one** file descriptor so there seems no change at all or could someone show me an app that does act like [this](https://apkpure.com/ping/com.lipinic.ping) ICMP based app without being meant to test site/net and without having bug then we agree with you

**Comment by M66B** [comment]
Thanks.

**Pull request merged**
