### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Ivan4537**

### CODE REVIEW

**Comment by M66B** [comment]
Didn't you update the texts on Crowdin as well?
There is no need to do a pull request then, since I will synchronized with Crowdin periodically.

**Comment by Ivan4537** [comment]
That's right, I update on Crowdin. But why is there I did not find the text translated now on Github. And I can't find and translate this text (a tick marked the most important text that I would like to translate). It's hidden in .smali?

**Comment by licaon-kter** [comment]
Strange: https://crowdin.com/translate/netguard/44/en-ru#906

The other are not in the strings yes.

**Comment by Ivan4537** [comment]
The sentence translated, but the app itself is in English...
And the words that are not in strings.xml will be available for translation ever?

**Comment by M66B** [comment]
The debug options and technical info headers are not translatable, so this is right.

The development options will only be available in beta build, but I have just made the headers of the technical info translatable.

**Comment by M66B** [comment]
The technical info header texts are no available for translation on Crowdin.

**Comment by Ivan4537** [comment]
Okay, thank you

**Pull request closed without merging**
