### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Ivan4537**
Update.
How about a line break, if it does not fit into one line? Half of text of <string name="setting_unused"> not visible. Or it will affect the visual component of the application?

### CODE REVIEW

**Comment by Ivan4537** [comment]
Half of text of /string name="setting_unused"/ not visible.

**Comment by M66B** [comment]
Thanks for keeping the translation up to date.

**Comment by M66B** [comment]
I will see what I can do about it

**Comment by Ivan4537** [comment]
Thanks!

**Comment by Ivan4537** [comment]
Here on this screenshot perfectly clear that the text is cut off. https://goo.gl/6vCb8R
Should be: "Разрешить сети, когда экран включен, по умолч."

**Comment by M66B** [comment]
Unfortunately it is not possible to change how a preference title is being displayed, so the text needs to be shorter somehow.

**Comment by Ivan4537** [comment]
Well, not scary. I think that the meaning of the menu item will still be clear. Thanks for the reply.

**Pull request merged**
