### PR TITLE
Change DNS + connectivity check

### PR DESCRIPTION
**Pull request by kasnder**
If I understand correctly, Google is unlikely to be contacted under normal operation of NetGuard.

This PR tries to reduce connections to Google further, for _privacy reasons_.

### CODE REVIEW

**Comment by licaon-kter** [comment]
I loled in real life, the f-droid.org is slow even when working, let's not use it as a beacon for anything really :)

Also, why would you fallback to CF of all things? Didn't it fall last month taking down 30% of the internet with it, c'mon.

Let's decentralize more... not less.

**Comment by M66B** [comment]
I can't agree more.

**Comment by kasnder** [comment]
Thank you for the prompt feedback. I completely agree with your criticism but don't think that's the point.

It's solely about considering *alternatives to Google* services, but thoroughly accept that you have a different view on this.

**Comment by theBubbly** [comment]
+1 for liberty and such

**Comment by M66B** [comment]
This pull request would change the defaults of existing settings only, so everybody already has the *liberty* to configure things differently.

**Pull request closed without merging**
