### PR TITLE
Decprecated AsyncTask has been replaced and Kotlin support added to the project.

### PR DESCRIPTION
**Pull request by it5prasoon**
1. :fire:  Added kotlin support to the project. 
2. :+1:  Activities and adapters has been converted to kotlin. 
3. :rocket: Deprecated AsyncTask is replaced by Kotlin CoroutineAsyncTask.

### CODE REVIEW

**Comment by licaon-kter** [comment]
So many deletion, did you forget to push some commits?

**Comment by it5prasoon** [comment]
> So many deletion, did you forget to push some commits?

No, I have changed the java files to kotlin. So it is showing deletion.

**Comment by licaon-kter** [comment]
Press the Files button above... only the deleted files are shown.

**Comment by it5prasoon** [comment]
Yeah I haven't pushed the older java files. You can make different branch for kotlin. When it is available to merge you can merge that.

**Comment by it5prasoon** [comment]
Yeah sorry. I haven't pushed all files. I am completing it now. 🥺

**Comment by it5prasoon** [comment]
Done.

**Comment by licaon-kter** [comment]
Maybe not commit `app/.cxx` and other files generated during build.

**Comment by it5prasoon** [comment]
> Maybe not commit `app/.cxx` and other files generated during build.

Yeah deleted. .cxx file. 👍

**Pull request closed without merging**
