### PR TITLE
Updated italian translation

### PR DESCRIPTION
**Pull request by marco-scavuzzo**

### CODE REVIEW

**Comment by M66B** [comment]
Something is not going as expected, since there are no files changed.

**Comment by marco-scavuzzo** [comment]
Sorry, it's my fault. In the rush I forgot to add italian strings.xml.
Fixing now

**Comment by M66B** [comment]
No worries and no hurry.

**Comment by M66B** [comment]
Thanks, you fixed it fast!

**Comment by marco-scavuzzo** [comment]
you're welcome ;)

**Pull request merged**
