### PR TITLE
Update FAQ#39 with https link

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by M66B** [comment]
Even if the data would be sent over an insecure connection, the data cannot be used to identify people, so IMHO this adds nothing.

**Comment by licaon-kter** [comment]
Adds peace of mind for the user...

**Comment by M66B** [comment]
To me this feels as misleading/confusing people.

I don't want to apply "_If you can't convince them, confuse them_" (https://en.wikiquote.org/wiki/Harry_S._Truman)

**Comment by licaon-kter** [comment]
It's not misleading, it just states the way things are.
Your data sharing is as secure as a Google Play store connection (although I did not go that far), to say a MITM, a global actor that just gathers data or such.

**Comment by M66B** [comment]
It is true that it states the way things are, but it also suggest that a secure connection and the data not being privacy sensitive are related to each other, which is untruthful.

Even with a MITM attack no privacy sensitive data can be revealed, because no privacy sensitive data is being sent at all.

**Pull request closed without merging**
