### PR TITLE
Add FAQ#39 reference to clarify tracking

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by M66B** [comment]
I know it is a kind of hot topic currently, but that is not a good reason to include this detail in the feature list.

**Comment by licaon-kter** [comment]
To me this feels as misleading/confusing people.

**Comment by M66B** [comment]
User are not and even cannot be profiled, so I don't see any misleading/confusion here.

**Comment by licaon-kter** [comment]
Their (in app) activity is tracked, the sum of that data is a profile.

**Comment by M66B** [comment]
True, but it is not a user profile, since no user information is being shared.

**Comment by licaon-kter** [comment]
Ok, you'll answer the Google Play store questions as you see fit then. :)

**Pull request closed without merging**
